// svelte/vite-svelte-js/src/App.svelte
<script lang="ts">
  import styled from "@/windboxes";
  import svelteLogo from "./assets/svelte.svg";
  import Counter from "./lib/Counter.svelte";

  const LogoLayoutClasses = styled("mb-10 flex items-center justify-center");

  const LogoClasses = styled(
    "w-28 m-5 hover:drop-shadow-[0_12px_2em_#646cffaa]"
  );
  const LogoSvelteClasses = styled(
    "w-28 m-5 hover:drop-shadow-[0_12px_2em_#ff3e00aa]"
  );
</script>

<main>
  <div class={LogoLayoutClasses}>
    <a href="https://vitejs.dev" target="_blank" rel="noreferrer">
      <img src="/vite.svg" class={LogoClasses} alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class={LogoSvelteClasses} alt="Svelte Logo" />
    </a>
    <div class="text-center" />
  </div>

  <h1>Vite + Svelte</h1>

  <div class="card">
    <Counter />
  </div>

  <p>
    Check out <a
      href="https://github.com/sveltejs/kit#readme"
      target="_blank"
      rel="noreferrer">SvelteKit</a
    >, the official Svelte app framework powered by Vite!
  </p>

  <p class="read-the-docs">Click on the Vite and Svelte logos to learn more</p>
</main>

// vue/vite-vue-ts/src/App.vue
<script setup lang="ts">
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://vuejs.org/api/sfc-script-setup.html#script-setup
import HelloWorld from './components/HelloWorld.vue'
import styled from './windboxes';

const logoLayoutClasses = styled('mb-10 flex align-center justify-center');

const logoClasses = 'w-20 h-20 m-5'.split(' ');
const viteLogoClasses = styled([...logoClasses, 'hover:drop-shadow-[0_0_2em_#646cffaa]']);
const vueLogoClasses = styled([...logoClasses, 'hover:drop-shadow-[0_0_2em_#42b883aa]']);
</script>



<template>
  <div :class="logoLayoutClasses">
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" :class="viteLogoClasses" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" :class="vueLogoClasses" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vite + Vue" />
</template>
